### PR TITLE
feat: add tracking to call to action button (#58)

### PR DESCRIPTION
**Pull request by frano-m**

### CODE REVIEW

**Comment by frano-m** [comment]
Hi @AyyazAli,

I’ve just completed a “work in progress” PR and assigned it to you. It should include some early framework for you to continue on with your tasks.

It is a WIP, so if you feel that some of the typescript is complaining, please let me know.

I have included a “test” of the new function `track` in `packages/data-explorer-ui/src/views/ExploreView/exploreView.tsx` on lines `71-75`. For some reason I am not seeing the result in the network tab. Note, I have not yet put tracking on the “Call To Action” button.

Some areas I think might need your eyes include:
- The function `track` in `packages/data-explorer-ui/src/common/analytics/analytics.ts` - could you please review in particular line `40` as I was not sure of the variable names for the event.

For linking the explorer to data-browser, increase the package version to `0.14.0`.

Please let me know if you have any questions. Thank you!

**Comment by AyyazAli** [comment]
For `track` in `packages/data-explorer-ui/src/views/ExploreView/exploreView.tsx` on lines 71-75, I was able to view the event trigger directly in GTM. It's not sending the request through network tab, it's doing it through dataLayer.

**Comment by NoopDog** [comment]
Thanks, @AyyazAli can you recommend a tool for viewing the datalayer updates locally, or is going to the GTM console the best way?

**Comment by NoopDog** [comment]
Will merge this work in a different branch.

**Pull request closed without merging**
